In [ ]:
#Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [13]:
n = int(input('Введите число '))

Введите число 10


In [19]:
a = np.arange(0, n)

In [20]:
np.flip(a, 0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [26]:
b = np.diag(np.arange(0, n), k = 0)
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [25]:
np.trace(b)

45

In [ ]:
#Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [27]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4]  ] )
b = np.array( [4, 12, 3] )

In [28]:
from numpy import linalg

In [29]:
linalg.solve(a, b)

array([-2.28,  4.76,  3.6 ])

In [30]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True